package com.pms.query;

public interface Query {
	
	String CREATE_PRODUCT= "INSERT INTO PRODUCT VALUES(?,?,?,?)";
	String SELECT_PRODUCT_ID = "SELECT * FROM PRODUCT WHERE PID=?";
	String SELECT_PRODUCTS = "SELECT * FROM PRODUCT";
	String UPDATE_PRODUCTS = "UPDATE PRODUCT SET PNAME=?, QTY=?, PRISE=? WHERE PID=?";
	String DELETE_PRODUCT_ID = "DELETE FROM PRODUCT WHERE PID=?";

}
